
:author: Phil White
:author_email: pwhite@mercy.edu
:revdate: August 20, 2020
:revnumber: 2.0

:toc: left
:toc-levels: 2
:toc-title: Contents

:sectnumlevels: 2

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:source-highlighter: pygments
:pygments-style: emacs
:icons: font


.AsciiDoc history
****
AsciiDoc was first released in Nov 2002 by Stuart Rackham.
It was designed from the start to be a shorthand syntax
for producing professional documents like DocBook and LaTeX.
****

last revision {revdate}

question? email {author_email}

.#Testing Asciidoctor# image:https://www.ahus1.de/_nuxt/img/asciidoctor.5b44175.svg[width="5%" title="Asciidoctor logo"]
****
As of {revdate} this document contains text that has been inserted only for the purpose of
testing https://asciidoc.org[AsciiDoc] and http://asciidoctor.org[Asciidoctor].
****

.After landing the cloaked Klingon bird of prey in Golden Gate park:
[quote, Captain James T. Kirk, Star Trek IV: The Voyage Home]
Everybody remember where we parked.

[quote, Monty Python and the Holy Grail]
____
Dennis: Come and see the violence inherent in the system. Help! Help! I'm being repressed!

King Arthur: Bloody peasant!

Dennis: Oh, what a giveaway! Did you hear that? Did you hear that, eh? That's what I'm on about! Did you see him repressing me? You saw him, Didn't you?
____

"I hold it that a little rebellion now and then is a good thing,
and as necessary in the political world as storms in the physical."
-- Thomas Jefferson, Papers of Thomas Jefferson: Volume 11

[%collapsible]
====
This content is only revealed when the user clicks the block title.
====

.Click to reveal the answer
[%collapsible]
====
This is the answer.
====

.Onomatopoeia
====
The book hit the floor with a *thud*.

He could hear doves *cooing* in the pine trees`' branches.
====

Press the btn:[OK] button when you are finished.

Select a file in the file navigator and click btn:[Open].

To save the file, select menu:File[Save].

Select menu:View[Zoom > Reset] to reset the zoom level to the default setting.

[horizontal]
Item 1::
Description 1

Item 2::
Description 2

* Item 1
+
Continuation text for the previous list item.

Multi line +
Hard Breaks +
More stuff

[%hardbreaks]
using `[%hardbreaks]`
Multi line
Hard Breaks
More stuff

.Monospace
Even within line `Macintosh HD/Users/Shared/Avid/UVI`, see.

.CODE Test XML
[source,xml]
----
<section>
  <title>Section Title</title> <!--1-->
</section>
----
<1> The section title is required.

.CODE Test app.rb
[source,ruby,linenums]
----
require 'sinatra'

def sum_eq_n?(arr, n)
  return true if arr.empty? && n == 0
  arr.product(arr).reject { |a,b| a == b }.any? { |a,b| a + b == n }
end
----

:sectnums!:
== Overview

---
.Optional Title
NOTE: Some stuff and some more stuff

link:++https://example.org/?q=[a b]++[URL with special characters]

link:https://example.org/?q=%5Ba%20b%5D[URL with special characters]

[[bookmark-a, inline]]Inline anchors make arbitrary content referenceable.

[#bookmark-b]#Inline anchors can be applied to a phrase like this one.#

anchor:bookmark-c[]Use a cross reference to link to this location.

See <<bookmark-a>> to learn how to write paragraphs.
See <<bookmark-d>> to go to elsewhere.

This +*literal*+ will appear as *literal*.

Inline pass macro and explicit substitutions

The text pass:[<u>underline me</u>] is underlined.

****
.Symbol characters

(C)
(TM)
(R)
em -- dash
...
->
=>
<-
<= +

Sam's (typographic apostrophe)
****
****
.LISTS
* Apples
* Oranges +
And other fruits

//-

* Walnuts
* Almonds
****
****
.Numbered list start other than 1
[start=4]
. Step four
. Step five
. Step six
****
****
[%reversed]
.Parts of an atom (reverse list using `[%reversed]`)
. Protons
. Electrons
. Neutrons
****
****
[upperroman, start=5]
. Five
. Six
[loweralpha, start=3]
.. a
.. b
.. c
. Seven
****
....
Literal text test
....


:sectnums:

[qanda]
.Q&A TEST
How many?::
More than you thunk.
Will there be more?::
Perhaps yes, perhaps no.
Is this an example of `[qanda]` in Asciidoc?::
Why yes, yes it is.


---
CPU:: The brain of the computer.
Hard drive:: Permanent storage for operating system and/or user files.
RAM:: Temporarily stores information the CPU uses during operation.
Keyboard:: Used to enter text or control items on the screen.
Mouse:: Used to point to and select items on your computer screen.
Monitor:: Displays information in visual form using text and graphics.
---
[horizontal]
.Horizontal
CPU:: The brain of the computer.
Hard drive:: Permanent storage for operating system and/or user files.
RAM:: Temporarily stores information the CPU uses during operation.

.Colors
[red]*Red*
[green]*Green*
[purple]*Purple*
[blue]*Blue*
[yellow]*Yellow*
[fuchsia]*Fuchsia*
[blue-background white]*Blue BG*

[red]#Obvious# and [big red yellow-background]*very obvious*.
[underline]#Underline text#, [overline]#overline text# and
[blue line-through]*bold blue and line-through*.

.Unconstrained quotes
She spells her name with an "`h`", as in Sara[red]**h**.

.Tables

|===

|Cell in column 1, row 1 |Cell in column 2, row 1

|Cell in column 1, row 2
|Cell in column 2, row 2

|===


[cols=".<,.^,.>"]
|===
|Column 1, row 1
|Column 2, row 1
|Cell in column 3, row 1 and plenty more to say and even more.

|Column 1, row 2
|Column 2, row 2
|Column 3, row 2 and whatever
|===


[block-diag]
....
                   +-------------+
                   | Asciidoctor |-------+
                   |   diagram   |       |
                   +-------------+       | PNG out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        | --+ Asciidoctor +--> |               |
 |  Text  |   +-------------+    |   Beautiful   |
 |Document|   |   !magic!   |    |    Output     |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
....



//  A single-line comment

last revision {revdate}

question? email {author_email}

Multi line +
Comment of +
More stuff

[%hardbreaks]
Multi line
Comment of
More stuff

.Testing Asciidoctor image:https://www.ahus1.de/_nuxt/img/asciidoctor.5b44175.svg[width="5%" title="Asciidoctor logo"]
****
As of {revdate} this document contains some text that has been inserted only for the purpose of
testing https://asciidoc.org[AsciiDoc] and http://asciidoctor.org[Asciidoctor].

AsciiDoc was first released in Nov 2002 by Stuart Rackham.
It was designed from the start to be a shorthand syntax
for producing professional documents like DocBook and LaTeX.
****

----
include::../Documentation/StudentandFacultyresources.adoc[lines=50..60]
----

[source,xml]
----
<section>
  <title>Section Title</title> <!--1-->
</section>
----
<1> The section title is required.

:sectnums!:
== Overview

.Optional Title
---

NOTE: Some stuff and some more stuff

link:++https://example.org/?q=[a b]++[URL with special characters]

link:https://example.org/?q=%5Ba%20b%5D[URL with special characters]

[[bookmark-a, inline]]Inline anchors make arbitrary content referenceable.

[#bookmark-b]#Inline anchors can be applied to a phrase like this one.#

anchor:bookmark-c[]Use a cross reference to link to this location.

See <<bookmark-a>> to learn how to write paragraphs.
See <<bookmark-d>> to go to elsewhere.
