:doctitle: MPRA Studio Policies

:author: Phil White
:author_email: pwhite&#064;mercy.edu
:revdate: September 7, 2023
:revnumber: 2.0

:toc: left
:toc-levels: 2
:toc-title: Studio Policies

:icons: font
:sectnumlevels: 2

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

// Disable last updated text.
// :last-update-label!:


NOTE: **Studio/Student Worker Phone Number**:  (914) 674-7767

## General Policies

* Only currently enrolled Music Production and Recording Arts Program may have access to facilities.

* Non-Mercy students and Non-Majors (guests) must have advanced approval from the Studio Manager or Program Director and must be accompanied by a major at all times.

* All students must request access from a department staff member (Staff or Student Worker) at the front desk and sign-in before entering Studio A, Studio B, Studio C or Studio D and sign-out when leaving.  (Leave your ID with Staff Member)

* All Sessions have a maximum of 2 hours.  (If you need longer sessions, email the Studio Manager)

* If you need to book a session more than 30 days in advance, please contact the Studio Manager.

* Lab stations in 203 and 204 are open to all students during Mercy University’s operational hours. This does not require a student to sign-in.

* No food, beverages, or smoking/vaping will be permitted in any department facilities.

* No equipment may leave the premises.

* Any misuse of facilities, or non-adherence to lab policies may result in the revoking of lab privileges and/or dismissal from the department.

* The student responsible for the session must be present during the entire session. All guests must be listed on the reservation (access at:  scheduler.labarchives.com)

* Booking sessions for others is prohibited.

* Student Workers are available to help with 10% of the session.  They are not available to run the whole session for a student.

* Students do not have access to the Studio Microphone Locker or Storage.

** See Student Worker or staff for microphones and equipment.

* Bring your own headphones to the studio and labs.

* Please practice studio etiquette. (Don’t walk into a performance area when artists are playing, knock on the door, etc.)


### Maintenance and Cleanup

At the end of your session, make sure chairs are pushed in.
No trash should be left in studio.
No mics, cables or headphones should be left out.
All equipment, including drum set and amps, must be organized by the end of the session.
All cables from headphone stations must be wrapped against the wall.
Quick release adapters must remain on stands and mic clips at all times.


## Studio Booking Policies

WARNING: The use of the facilities for personal projects is a privilege granted by the Music Production and Recording Arts Program Staff. Sessions may be cancelled without notice, or interrupted by the Staff in the event of urgent department business.

### Studio Access Policy

#### Session Priority

Priority is given in the following order:

. Music Production and Recording Arts classes
. Instructor preparation time (generally one hour prior to class)
. Student lab time slots, or sessions booked for class projects
. Departmental use (such as time for maintenance, prospective student tours, etc.)
. Pre-arranged (reserved) student sessions
. Walk-in student sessions

#### Computer Labs

All Students have unrestricted access to Victory Hall 203 and 204 (Lab stations) during normal operating hours.

#### Studio A Access
Access to Studio A is granted after passing Studio Workshop Proficiency Exam
You must be enrolled in or have completed MTEC 220 Recording Studio Workshop I
Certain microphones are only for Studio A use (Royer, Neumann, Rode NTK)

#### Studio B Access

Access to Studio B is granted once you are in Audio production III MTEC 301

#### Studio C and D Access
Access to Studio C and D is granted after passing Studio Access Orientation. (See the Studio Manager to schedule an orientation.)

#### “Walk-In” Sessions
* Walk-in sessions are limited to MPRA majors only. Not for guests.
* Walk-in sessions have a maximum length of two hours. At the end of two hours, the primary student may book a second two-hour session, IF no one else has requested the room.
* Walk-in sessions cannot be booked in advance and are permitted on a “first-come, first-served” basis only.
** A student must appear in person to request a walk-in session.
** If a studio is currently in use, a student may reserve the next available opening and must be present 10 minutes prior to the conclusion of the previous session.

#### Pre-Booked Sessions

To request a session in advance, visit https://scheduler.labarchives.com[Studio  Scheduler]

* Personal sessions must be booked a minimum of one business day in advance using the online session request form.
  ** Sessions will only be approved during business hours, Monday-Friday.

WARNING: If you are more than 15 minutes late for your booked session, you forfeit your booked time.

Studio Operating Hours (Victory Hall Building)
Monday through Friday 09:30am – 11:00pm
Saturdays 10:00am – 11:00pm

* Be ready to leave by 11:00pm.
** Give yourself enough time to clean up your session.

WARNING: Student privileges may be suspended for reasons including the misuse of the facilities or equipment, excessive missed bookings, or failure to adhere to department policies.

* Please do not book a session and not show up.
* If you are going to be late or miss your session please call the student worker studio phone [green]*(914) 674-7767*.
* You can cancel your session 24 hours prior to the session online without penalty.
* More than two missed Pre-Booked Personal Sessions will forfeit your ability to book personal sessions for one month.


#### Program Graduates

Graduates of the Music Production and Recording Arts Program have access to Victory Hall rooms 203 and 204 only, as long as it doesn’t interfere with classes or projects.