:author: Phil White
:author_email: pwhite&#064;mercy.edu
:revdate: February 24, 2021
:revnumber: 2.0

:toc: left
:toc-levels: 2
:toc-title: Online Scheduler

:icons: font
:sectnumlevels: 2

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

include::incl/variables.adoc[]



= Booking time in Classroom/Labs and Recording Studios

Music Production+Recording Arts students and faculty should receive an invitation to create an account. If you have not received the invitations, check your Spam or Junk folder first and then email {author_email}.

// tag::safety[]

* To facilitate safety, when classes are not in session, [red]*all time spent in classroom/labs* (as well as recording studios) [red]*must be reserved* using our {booked_site}[online scheduler].

** Strict limits on room occupancy will be enforced.

NOTE: https://youtu.be/5cl2wxJ2Rg0[Here is a video] on how to use the scheduling system.

// tag::safety[]

// tag::newaccount[]

. Go to https://scheduler.labarchives.com/
. Input your Mercy email address and click "next"
. You will be prompted to login using your Mercy single sign-on credentials.
. When brought to the LabArchives Login setup page, input your Mercy email address and click "Create New Account"
. When asked “Do you want to create a new LabArchives account?” Click “Yes.”
. After this, your LabArchives account will be connected to the Single Sign-On for Mercy. Each time you login through the Single Sign-On you will be brought directly to your account.

// end::newaccount[]

:sectnums:
