:doctitle: MPRA Studio Policies

:author: Phil White
:author_email: pwhite&#064;mercy.edu
:revdate: September 7, 2023
:revnumber: 2.0

:toc: left
:toc-levels: 2
:toc-title: Studio Policies

:icons: font
:sectnumlevels: 2

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

// Disable last updated text.
// :last-update-label!:


NOTE: **Studio/Student Worker Phone Number**:  [green]*(914) 674-7767*

## General Policies

* Only students currently enrolled in the Music Production and Recording Arts Program may request access to facilities.

* All Non-Mercy students and Non-Majors (i.e., session guests) must have advanced approval from the Studio Manager or Program Director and must be accompanied by a major at all times.

* When arriving for a session, all students must check in with a program staff member (Staff or Student Worker) at the front desk and sign-in before entering Studio A, Studio B, Studio C or Studio D and sign-out when leaving. (Leave your ID with Staff Member)

* Lab stations in 203 and 204 are open to all students during Mercy University’s operational hours. A student does not need to sign-in to use these labs.

* No food, beverages, or smoking/vaping will be permitted in any department facilities.

* No equipment may leave the premises.

* Any misuse of facilities, or non-adherence to policies may result in the revoking of privileges and/or dismissal from the department.

* Student Workers are available to help with 10% of the session.  They are not available to run the whole session for a student.

* Students who book the session do not have access to the Studio Microphone Locker or Storage.

** See Student Worker or staff for microphones and equipment.

* Bring your own headphones to the studio and labs.

* Please practice studio etiquette. (Don’t walk into a performance area when artists are playing, don't knock on the door, etc.)

// Add separate etiquette document?

#### Maintenance and Cleanup

NOTE:	You are expected to leave the studio in the same condition as you found it (or better).

* At the end of your session, make sure chairs are pushed in.

* No trash should be left in studio.

* No mics, cables or headphones should be left out.

** All cables must be properly wrapped.

* All equipment, including drum set and amps, must be organized by the end of the session.

* All cables from headphone stations must be wrapped against the wall.

* Quick release adapters must remain on stands and mic clips at all times.

### Studio Access Policies

#### Computer Labs

Music Production & Recording Arts Students have unrestricted access to Victory Hall 203 and 204 (Lab stations) during normal building hours.

#### Studio A Access

Access to Studio A is granted after passing _Studio Workshop Proficiency Exam_.

You must be enrolled in or have completed _MTEC 220 Recording Studio Workshop I_.

Certain microphones are reserved for use only in Studio A (Royer, Neumann, Rode NTK).

#### Studio B Access

Access to Studio B is granted once you are in _Audio production III MTEC 301_

#### Studio C and D Access
Access to Studio C and D is granted after passing _Studio Access Orientation_. (See the Studio Manager to schedule an orientation.)

NOTE: *Program Graduates* +
Graduates of the Music Production and Recording Arts Program have access to Victory Hall rooms 203 and 204 _only_, as long as it doesn’t interfere with classes or projects.

## Studio Booking Policies

---
[.text-center]
*Studio Operating Hours* +
(Victory Hall Building) +
 +
*Monday* through *Friday* +
09:30am -- 11:00pm
 +
*Saturday* +
10:00am -- 11:00pm
 +
*Sunday* +
CLOSED

---

WARNING: The use of the facilities for personal projects is a privilege granted by the Music Production and Recording Arts Program. +
 +
 The MPRA Program reserves the right to cancel or interrupt sessions without prior notice in the event of weather, a lack of staffing, or other emergencies. Every reasonable effort will be made to reschedule these sessions, when possible.

### Session Priority

Priority is given in the following order:

. Music Production and Recording Arts classes, workshops, and scheduled guest lectures.
. Instructor preparation time (studios are generally reserved one hour prior to class).
. Student lab time slots, or sessions booked for course projects
. Departmental use (such as time for maintenance, prospective student tours, etc.)
. Pre-arranged (reserved) faculty sessions
. Pre-arranged (reserved) student sessions
. Walk-in student sessions

### Pre-Booked Sessions

In order to reserve studio time, you must book it several days ahead of the session. To request a session in advance, visit https://scheduler.labarchives.com[Studio  Scheduler]

* Personal sessions must be booked a minimum of one business day in advance using the online session request form.
  ** Sessions will only be approved during business hours, Monday-Friday.

* Sessions normally have a maximum of 2 hours. (If you need longer sessions, email the Studio Manager)

* If you need to book a session more than 30 days in advance, please contact the Studio Manager.

* The student responsible for the session must be present during the entire session. All guests must be listed on the reservation (access at: scheduler.labarchives.com)

* Booking sessions for others is prohibited.

WARNING: If you are more than 15 minutes late for your booked session, you forfeit your booked time.

* Be ready to leave before closing time.
** To do this, you will need to end your session 10–15 minutes early to allow enough time to clean up your session, back up files, etc.

WARNING: Student privileges may be suspended for reasons including the misuse of the facilities or equipment, excessive missed bookings, or failure to adhere to department policies.

* You are expected to show up on time for all reserved sessions. Do not book a session you cannot attend. If you know you must miss a session due to sudden illness or some other unforeseen circumstance, please cancel the session prior to the start time by calling the student worker studio phone at [green]*(914) 674-7767*.

* If you are going to be late for the start of your session please call the student worker studio phone [green]*(914) 674-7767*.

* You can cancel your session 24 hours or more prior to the session online without penalty.

* More than two missed Pre-Booked Personal Sessions will forfeit your ability to book personal sessions for one month.

### “Walk-In” Sessions

Walk-in sessions can occur when a studio has not been reserved in advance, or when a reserved session has been cancelled.

MPRA students in good standing may request to use the studios on a walk-in basis, with the following provisions:

* Walk-in sessions are limited to MPRA majors only. Session guests are not allowed.
* Walk-in sessions have a maximum length of two hours.
** Ten minutes before the end of the initial two-hour session, a student may request to extend the walk-in session to a second two-hour period, assuming no one else has requested the room.

//[clarify what happens when the second request to use the room occurs during the initial two hours—encourage parties to work out a mutually acceptable outcome?]

* Walk-in sessions cannot be booked in advance and are permitted on a “first-come, first-served” basis only.
** A student must appear in person to request a walk-in session.
** If a studio is in use, a student may reserve the next available opening and must be present 10 minutes prior to the conclusion of the previous session.